apiVersion: apps/v1                    # We’re managing higher‑level Deployment objects
kind: Deployment                       # A Deployment maintains a ReplicaSet of Pods
metadata:
  name: backend                        # Unique name in the cluster
  labels:
    app: backend                       # Labels let Services/other controllers find it
spec:
  replicas: 2                          # Desired number of Pods running at any time
  selector:
    matchLabels:
      app: backend                     # This ties the Deployment to Pods with this label
  template:                            # Pod “template”—defines how each Pod should look
    metadata:
      labels:
        app: backend                   # Must match the selector above
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend                # Identifier for this container within the Pod
          image: ghcr.io/alanbjordan/veteran-support-agent-backend:latest                          
          ports:
            - containerPort: 5000      # Expose port 5000 inside the Pod
          env:
            - name: CORS_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: CORS_ORIGINS
          envFrom:
            - secretRef:
                name: backend-secrets  # Inject all entries from the Secret as ENV vars
          readinessProbe:              # ensures Pod is “Ready”
            httpGet:
              path: /api/chat-check
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10