name: Build & Push Docker Images

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  ORG: alanbjordan
  VERSION: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/alanbjordan/veteran-support-agent-backend:latest
            ghcr.io/alanbjordan/veteran-support-agent-backend:${{ github.sha }}

      - name: Build & Push Client
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/alanbjordan/veteran-support-agent-frontend:latest
            ghcr.io/alanbjordan/veteran-support-agent-frontend:${{ github.sha }}
          build-args: |
            REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}